/**
 * The sitemap and robots.txt nginx serves, regenerated and compared.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * WHY THE BODIES ARE IN nginx.conf AT ALL
 *
 * A sitemap must carry ABSOLUTE URLs — the spec requires it and a crawler discards a relative
 * `<loc>` — and nothing built in this repository may name a hostname, because one image is served
 * from localhost, from a preview deployment and from `trade.<apex>`. `test/no-build-time-config.
 * test.ts` is the rule; this is the one document that would otherwise have to break it.
 *
 * nginx is the component that knows. It has `$host` on every request, so the bodies are composed
 * per request from a config file with no hostname in it.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * AND WHY THIS SURFACE IS NOT THE MARKETING SITE
 *
 * `site` serves the ESTATE sitemap, generated by `sitemapXml()` from the surface registry, and it
 * can because `site` is the apex: `$host` is the apex there and every sibling is a prefix on it.
 * Here `$host` is already `trade.<apex>`, so the same helper would compose
 * `foresight.trade.<apex>` — a two-label name nothing resolves and that Cloudflare's one-label
 * wildcard certificate could not terminate. So this surface emits ITS OWN public routes and
 * nothing else, and the test below is written against that decision rather than against the
 * shared generator: `robotsTxt()` is still regenerated byte for byte, because that one is not a
 * function of the registry at all.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * WHICH ROUTES ARE IN IT IS NOT A JUDGEMENT MADE HERE
 *
 * `src/lib/routes.ts` already carries `public` per route, and it carries it because the SERVICE
 * decides: `GET /v1/strategies` makes no `authenticate()` call, and everything under /backtests
 * and /bots does. A sitemap listing a `ProtectedRoute` invites a crawler to an address that can
 * only answer it with a sign-in redirect, and a crawler handed dead ends by a site's own index
 * discounts the ones that work.
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 */
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { describe, it } from 'node:test'
// From `/surfaces` rather than from the package root: this file has no DOM and needs none, and the
// root entry point pulls in every React component in the design system to reach one Set.
import { ENV_LABELS } from '@cloudsforge/ui/surfaces'
import { BASE, ROUTES, publicPath } from '../src/lib/routes.ts'

const nginx = readFileSync(new URL('../nginx.conf', import.meta.url), 'utf8')

/**
 * The address of a route on THIS surface, composed the way nginx composes it.
 *
 * ── `https` IS A LITERAL AND THE MOUNT IS PART OF THE ADDRESS ──────────────────────────────────
 *
 * `$scheme` was a live defect: TLS ends at Cloudflare and every hop after it is plaintext, so
 * `$scheme` is `http` for a reader who arrived over `https` and every `<loc>` advertised an
 * address that 301s. Found in micro-site in wave 1, exchange-web in wave 2 and market-web in
 * wave 3a; this is the fourth copy. `$host` stays a variable — the host genuinely differs.
 *
 * And the surface is `<apex>/trade` now, so a route's public address carries the mount.
 * `publicPath()` in `src/lib/routes.ts` is the one crossing and this mirrors it.
 */
const address = (path: string): string => `https://$host${publicPath(path === '' ? '/' : `/${path}`)}`

/** The single-quoted body of a `return 200 '…';` inside an exact-match location. */
function servedBody(path: string): string {
  const block = new RegExp(
    `location = ${path.replace('.', '\\.')} \\{([\\s\\S]*?)\\n    \\}`,
  ).exec(nginx)
  assert.ok(block, `nginx.conf has no exact-match location for ${path}`)
  // Anchored to a `return` at the start of its own line: `/robots.txt` also carries a CONDITIONAL
  // `if ($cf_env) { return 200 '…'; }` above it, and a regex that took the first match would read
  // the non-mainnet body and report the mainnet one as drifted.
  const body = /\n {8}return 200 '([\s\S]*?)';/.exec(block[1] ?? '')
  assert.ok(body, `the ${path} location does not return an unconditional literal body`)
  return body[1] ?? ''
}

/** Every `<loc>` in the document nginx actually returns — read from the body, never from the file. */
const locations = (): string[] =>
  [...servedBody(`${BASE}/sitemap.xml`).matchAll(/<loc>([^<]*)<\/loc>/g)].map((m) => m[1] ?? '')

describe('the sitemap nginx serves', () => {
  it('lists something at all, so nothing below can pass on an empty document', () => {
    assert.ok(locations().length >= 1, 'the sitemap has no <loc> in it')
  })

  it('names no hostname — every address is composed from $host', () => {
    /*
     * THE ASSERTION THAT KEEPS THE ARTEFACT ENVIRONMENT-FREE, and the reason this arrangement is
     * allowed at all. A single literal apex here would make the image wrong on a preview
     * deployment and on testnet, silently, in the one document a crawler treats as authoritative.
     */
    const xml = servedBody(`${BASE}/sitemap.xml`)
    assert.ok(!xml.includes('cloudsforge.online'), 'the sitemap names the production apex')
    assert.ok(!xml.includes('localhost'), 'the sitemap names localhost')
    for (const loc of locations()) {
      assert.match(loc, /^https:\/\/\$host/, `a <loc> is not composed from $host: ${loc}`)
    }
  })

  it('lists every PUBLIC route of this surface', () => {
    const xml = servedBody(`${BASE}/sitemap.xml`)
    const publicPaths = ROUTES.filter((r) => r.public).map((r) => r.path)
    assert.ok(publicPaths.length >= 1, 'the route table declares no public route')
    for (const path of publicPaths) {
      assert.ok(
        xml.includes(`<loc>${address(path)}</loc>`),
        `/${path} is public and is missing from the sitemap`,
      )
    }
  })

  it('lists NOTHING that is gated, because a crawler cannot open it', () => {
    // The half that actually decays. A route promoted to public without this file following is a
    // catalogue page nobody finds; a gated one added here is a sitemap of sign-in redirects.
    const xml = servedBody(`${BASE}/sitemap.xml`)
    for (const route of ROUTES) {
      if (route.public) continue
      assert.ok(
        !xml.includes(`<loc>${address(route.path)}</loc>`),
        `/${route.path} is a ProtectedRoute and must not be in the sitemap`,
      )
    }
    assert.equal(
      locations().length,
      ROUTES.filter((r) => r.public).length,
      'the sitemap lists an address that is not a public route of this surface',
    )
  })

  it('does NOT compose a sibling surface, because this host is not the apex', () => {
    // `sitemapXml()` would, and it is right to on `site` and wrong to here: $host is already
    // `trade.<apex>`, so a prefixed sibling is a two-label name nothing resolves.
    for (const loc of locations()) {
      assert.doesNotMatch(loc, /^\$scheme:\/\/[a-z-]+\.\$host/, `${loc} prefixes a sibling onto $host`)
    }
  })

  it('is served as XML, because a sitemap sent as text/html is a sitemap nobody reads', () => {
    // `types { }` as well as `default_type`: without emptying the table for this location, nginx
    // maps the `.xml` in the URI to `text/xml` from its own mime types and `default_type` never
    // applies.
    assert.match(
      nginx,
      new RegExp(`location = ${BASE}/sitemap\\.xml \\{[\\s\\S]*?types \\{ \\}[\\s\\S]*?default_type application/xml;`),
    )
  })
})

describe('an environment that is not mainnet', () => {
  /**
   * The `map` that decides it, and the alternation of labels inside it.
   *
   * A non-mainnet estate carries test EMBER, a faucet and deliberately broken states. Indexing it
   * puts a second, wrong copy of this product in front of anybody searching for the real one,
   * which is a support problem before it is an SEO problem.
   */
  function alternation(): string[] {
    const map = /map \$host \$cf_env \{[\s\S]*?~\^[^\n]*?\(\?:([^)]*)\)\\\./.exec(nginx)
    assert.ok(map, 'the $cf_env map is missing from nginx.conf')
    return (map[1] ?? '').split('|')
  }

  it('recognises exactly the labels the registry reserves', () => {
    /*
     * ENV_LABELS is the estate's single list — `deploy/scripts/check-apex-prefix.py` reads the same
     * export. An alternation here that had drifted from it would either miss an environment (and
     * index it) or refuse a surface (and de-index a real one), and both fail silently.
     */
    assert.deepEqual(alternation().sort(), [...ENV_LABELS].sort())
  })

  it('refuses every crawler and serves no sitemap', () => {
    // Both halves matter and neither is sufficient: robots.txt stops the fetch, and a 404 on the
    // sitemap stops the crawler being handed the addresses anyway.
    // ── THE robots.txt HALF IS micro-site's NOW, AND ONLY THE SITEMAP HALF IS STILL OURS ──────
    //
    // Both halves still matter: robots.txt stops the fetch, the 404 stops the document being there
    // to fetch, and a page that is only disallowed can still be indexed from an inbound link. But
    // a crawler reads robots.txt at the ORIGIN ROOT, so since this surface became `<apex>/trade`
    // its copy would be a file nothing fetches. micro-site owns that half and asserts it; the
    // sitemap half is asserted here because it is still this image's to serve.
    assert.match(
      nginx,
      new RegExp(`location = ${BASE}/sitemap\\.xml \\{[\\s\\S]*?if \\(\\$cf_env\\) \\{ return 404; \\}`),
    )
  })

  it('matches a suffixed subdomain as well as a bare environment apex', () => {
    // The environment is a SUFFIX on the first label now (`trade-testnet.`), and was an apex
    // prefix (`testnet.`) before. Both shapes still resolve — surfaces.ts keeps the old one
    // deliberately — so the pattern has to catch both or this surface stays indexable on testnet.
    const map = /map \$host \$cf_env \{[\s\S]*?\n\}/.exec(nginx)
    assert.ok(map, 'the $cf_env map is missing')
    assert.match(map[0], /\(\?:\[\^\.\]\+-\)\?/, 'the map does not allow a suffixed subdomain')
  })
})

describe('robots.txt', () => {
  it('is not served by this image at all, because the origin root is micro-site\'s', () => {
    /*
     * ── THE BLOCK THAT WAS HERE IS GONE, AND SO IS THE ONE IN nginx.conf ────────────────────────
     *
     * This asserted that `location = /robots.txt` regenerated `robotsTxt()` byte for byte and
     * carried an absolute `Sitemap:` line. Both were right while this surface was a hostname.
     *
     * A crawler reads robots.txt at the ORIGIN ROOT and nowhere else. Now that the surface is
     * `<apex>/trade`, `/trade/robots.txt` is a file nothing would ever fetch — so the rules were
     * not relocated, they STOPPED BEING THIS BUNDLE'S TO MAKE. micro-site owns `/robots.txt` on
     * this origin, its copy decides whether this surface is indexed, and its own suite asserts
     * that the `Sitemap:` line for every consolidated surface is there.
     *
     * What is asserted here is the absence, both ways: no location in nginx.conf, and no static
     * file either. An unreachable config file is not a safety net — it is a thing a future reader
     * finds, believes, and reasons from.
     */
    // Read with COMMENTS STRIPPED. The block that was deleted left a comment saying so, and that
    // comment necessarily contains the words `location = /robots.txt` — a raw-text search finds
    // its own explanation and reports the block as still present.
    const directives = nginx
      .split('\n')
      .filter((l) => !/^\s*#/.test(l))
      .join('\n')
    assert.ok(
      !/location = \/(?:trade\/)?robots\.txt/.test(directives),
      'this image serves a robots.txt again; the origin root is micro-site\'s',
    )
    assert.equal(
      existsSync(new URL('../public/robots.txt', import.meta.url)),
      false,
      'public/robots.txt is back, and nothing on this origin would fetch it',
    )
  })
})
